"""initial schema

Revision ID: 001_initial
Revises:
Create Date: 2026-08-09

Hand-written (not autogenerated): the pgvector extension, the hnsw index,
and the trigram index are not expressible through the SQLAlchemy ORM, so
every statement here is the exact SQL from implementation_plan.md section
6.1, run via op.execute(). See docs/architecture.md for the note on
LangGraph's checkpoint tables, which this migration does not create.
"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # A run represents one execution of the agent over a corpus.
    op.execute(
        """
        CREATE TABLE runs (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            corpus_id UUID NOT NULL,
            kind TEXT NOT NULL CHECK (kind IN ('initial', 'update')),
            status TEXT NOT NULL CHECK (status IN (
                'pending', 'running', 'awaiting_review', 'committing', 'done', 'failed', 'cancelled'
            )),
            parent_run_id UUID REFERENCES runs(id),
            triggering_document_id UUID,      -- for update runs
            started_at TIMESTAMPTZ DEFAULT now(),
            completed_at TIMESTAMPTZ,
            error TEXT,
            idempotency_key TEXT UNIQUE       -- for concurrent-safe API
        )
        """
    )

    op.execute("CREATE INDEX idx_runs_corpus_status ON runs(corpus_id, status)")

    # A corpus is a named collection of documents (one deliverable per corpus).
    op.execute(
        """
        CREATE TABLE corpora (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            name TEXT NOT NULL,
            inbox_path TEXT NOT NULL,
            rules_path TEXT,                  -- path to the checklist/playbook
            created_at TIMESTAMPTZ DEFAULT now()
        )
        """
    )

    # A document is a single file that has been ingested.
    op.execute(
        """
        CREATE TABLE documents (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            corpus_id UUID NOT NULL REFERENCES corpora(id),
            filename TEXT NOT NULL,
            content_hash TEXT NOT NULL,       -- sha256; dedupe by this
            mime_type TEXT NOT NULL,
            doc_type TEXT,                    -- classified: 'prd', 'techspec', 'ticket', ...
            ingested_at TIMESTAMPTZ DEFAULT now(),
            UNIQUE (corpus_id, content_hash)  -- same file twice = same document
        )
        """
    )

    # A chunk is a passage of a document with a stable location for citations.
    op.execute(
        """
        CREATE TABLE chunks (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            document_id UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
            idx INT NOT NULL,                 -- position within the document
            text TEXT NOT NULL,
            page INT,                         -- for PDFs
            char_start INT NOT NULL,
            char_end INT NOT NULL,
            embedding vector(1536),           -- match your embedding model
            UNIQUE (document_id, idx)
        )
        """
    )

    op.execute(
        "CREATE INDEX idx_chunks_embedding ON chunks USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute("CREATE INDEX idx_chunks_text_trgm ON chunks USING gin (text gin_trgm_ops)")

    # A claim is a fact the agent believes about the world, sourced.
    op.execute(
        """
        CREATE TABLE claims (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            run_id UUID NOT NULL REFERENCES runs(id),
            corpus_id UUID NOT NULL REFERENCES corpora(id),
            subject TEXT NOT NULL,            -- feature name / epic
            predicate TEXT NOT NULL,          -- 'has_owner', 'targets_release', ...
            object TEXT NOT NULL,             -- 'Jane Doe', '2026-Q3', ...
            confidence REAL NOT NULL,
            created_at TIMESTAMPTZ DEFAULT now(),
            superseded_by UUID REFERENCES claims(id)
        )
        """
    )

    # Every claim traces to one or more chunks.
    op.execute(
        """
        CREATE TABLE claim_sources (
            claim_id UUID NOT NULL REFERENCES claims(id) ON DELETE CASCADE,
            chunk_id UUID NOT NULL REFERENCES chunks(id) ON DELETE CASCADE,
            quote TEXT NOT NULL,              -- the exact text supporting the claim
            PRIMARY KEY (claim_id, chunk_id)
        )
        """
    )

    # Conflicts: two claims about the same (subject, predicate) with different objects.
    op.execute(
        """
        CREATE TABLE conflicts (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            run_id UUID NOT NULL REFERENCES runs(id),
            subject TEXT NOT NULL,
            predicate TEXT NOT NULL,
            claim_a_id UUID NOT NULL REFERENCES claims(id),
            claim_b_id UUID NOT NULL REFERENCES claims(id),
            resolution TEXT CHECK (resolution IN ('unresolved', 'kept_a', 'kept_b', 'kept_both', 'rejected_both')),
            resolved_by TEXT,                 -- 'human:<email>' or 'system:auto'
            resolved_at TIMESTAMPTZ
        )
        """
    )

    # Findings: rule violations from movement 2.
    op.execute(
        """
        CREATE TABLE findings (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            run_id UUID NOT NULL REFERENCES runs(id),
            rule_id TEXT NOT NULL,            -- from the checklist
            severity TEXT NOT NULL CHECK (severity IN ('info', 'warning', 'error')),
            subject TEXT,
            message TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
            reviewer TEXT,
            reviewed_at TIMESTAMPTZ
        )
        """
    )

    op.execute(
        """
        CREATE TABLE finding_sources (
            finding_id UUID NOT NULL REFERENCES findings(id) ON DELETE CASCADE,
            chunk_id UUID REFERENCES chunks(id),
            claim_id UUID REFERENCES claims(id)
        )
        """
    )

    # The register (the deliverable). One row per feature, mostly derived from claims.
    op.execute(
        """
        CREATE TABLE register_entries (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            corpus_id UUID NOT NULL REFERENCES corpora(id),
            feature_key TEXT NOT NULL,        -- stable identifier
            fields JSONB NOT NULL,            -- owner, release, status, risks, etc.
            version INT NOT NULL DEFAULT 1,
            last_updated_run_id UUID REFERENCES runs(id),
            updated_at TIMESTAMPTZ DEFAULT now(),
            UNIQUE (corpus_id, feature_key)
        )
        """
    )

    # Every register field remembers which claims backed it, for incrementality.
    op.execute(
        """
        CREATE TABLE register_field_sources (
            register_entry_id UUID NOT NULL REFERENCES register_entries(id) ON DELETE CASCADE,
            field_name TEXT NOT NULL,
            claim_id UUID NOT NULL REFERENCES claims(id),
            PRIMARY KEY (register_entry_id, field_name, claim_id)
        )
        """
    )

    # Reviews: what the human decided at the gate.
    op.execute(
        """
        CREATE TABLE reviews (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            run_id UUID NOT NULL REFERENCES runs(id),
            item_type TEXT NOT NULL CHECK (item_type IN ('claim', 'conflict', 'finding', 'register_change')),
            item_id UUID NOT NULL,
            decision TEXT NOT NULL CHECK (decision IN ('approve', 'reject')),
            note TEXT,
            reviewer TEXT NOT NULL,
            decided_at TIMESTAMPTZ DEFAULT now()
        )
        """
    )

    # Audit log: what changed, when, because of which source.
    op.execute(
        """
        CREATE TABLE audit_events (
            id BIGSERIAL PRIMARY KEY,
            run_id UUID REFERENCES runs(id),
            event_type TEXT NOT NULL,
            payload JSONB NOT NULL,
            occurred_at TIMESTAMPTZ DEFAULT now()
        )
        """
    )

    op.execute("CREATE INDEX idx_audit_run ON audit_events(run_id)")

    # Costs: token counts, latency, per stage.
    op.execute(
        """
        CREATE TABLE cost_events (
            id BIGSERIAL PRIMARY KEY,
            run_id UUID NOT NULL REFERENCES runs(id),
            stage TEXT NOT NULL,
            model TEXT NOT NULL,
            input_tokens INT NOT NULL,
            output_tokens INT NOT NULL,
            latency_ms INT NOT NULL,
            usd_cost NUMERIC(10, 6) NOT NULL,
            occurred_at TIMESTAMPTZ DEFAULT now()
        )
        """
    )

    op.execute("CREATE INDEX idx_cost_run ON cost_events(run_id)")

    # LangGraph checkpoints. LangGraph's Postgres saver creates its own tables;
    # you just point it at the same database and it manages them.


def downgrade() -> None:
    # Reverse dependency order: children before the tables they reference.
    op.execute("DROP TABLE IF EXISTS cost_events")
    op.execute("DROP TABLE IF EXISTS audit_events")
    op.execute("DROP TABLE IF EXISTS reviews")
    op.execute("DROP TABLE IF EXISTS register_field_sources")
    op.execute("DROP TABLE IF EXISTS register_entries")
    op.execute("DROP TABLE IF EXISTS finding_sources")
    op.execute("DROP TABLE IF EXISTS findings")
    op.execute("DROP TABLE IF EXISTS conflicts")
    op.execute("DROP TABLE IF EXISTS claim_sources")
    op.execute("DROP TABLE IF EXISTS claims")
    op.execute("DROP TABLE IF EXISTS chunks")
    op.execute("DROP TABLE IF EXISTS documents")
    op.execute("DROP TABLE IF EXISTS corpora")
    op.execute("DROP TABLE IF EXISTS runs")

    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    op.execute("DROP EXTENSION IF EXISTS vector")
